---
- name: Create cron job
  hosts: localhost
  tasks:
    - name: create new directory
      file:
        path: /root/crons
        state: directory

    - name: creating the scripts
      template:
        src: crons-cpu.j2
        dest: /root/crons/cpu_mem.sh
        mode: 0755
        
